name: Development

on:
  pull_request:

jobs:
  test-and-build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test-and-build
        with:
          PUBLIC_POSTHOG_PROJECT_TOKEN: ${{ vars.PUBLIC_POSTHOG_PROJECT_TOKEN }}
          PUBLIC_POSTHOG_HOST: ${{ vars.PUBLIC_POSTHOG_HOST }}

  # Disable for now since e2e does not work, will be re-enabled in a future PR after fixing the underlying issues with the tests and/or CI environment
  # e2e:
  #   runs-on: self-hosted
  #   needs: test-and-build

  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/e2e

  #     - name: Upload Playwright report
  #       uses: actions/upload-artifact@v4
  #       if: failure()
  #       with:
  #         name: playwright-report
  #         path: playwright-report/
  #         retention-days: 7

  docker-build:
    runs-on: self-hosted
    needs: test-and-build

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: ghcr.io/count-collab/count-collab:latest
          build-args: |
            PUBLIC_POSTHOG_PROJECT_TOKEN=${{ vars.PUBLIC_POSTHOG_PROJECT_TOKEN }}
            PUBLIC_POSTHOG_HOST=${{ vars.PUBLIC_POSTHOG_HOST }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
