name: Test and Build on Pull Request

on:
  pull_request:

jobs:
  test-and-build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test-and-build

  docker-build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: ghcr.io/count-collab/count-collab:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
